RandomQuotes/Models/BaseEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RandomQuotes.Models
{
    public class BaseEntity
    {
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

RandomQuotes/Models/ErrorViewModel.cs
using System;

namespace RandomQuotes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RandomQuotes/Models/QuotesList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RandomQuotes.Models
{
    public class QuotesList
    {
        private static List<QuotesViewModel> QuotesDb = new List<QuotesViewModel>() {
            new QuotesViewModel()
            {
                Quote = "Do not Despise the days of your little beginning",
                Author = "Annonynous"
            },

            new QuotesViewModel()
            {
                Quote = "He who fights and run away, must come back another day",
                Author = "Annonynous"
            },

            new QuotesViewModel()
            {
                Quote = "There is only one thing to do now",
                Author = "Annonynous"
            },

            new QuotesViewModel()
            {
                Quote = "However it goes, we will see",
                Author = "Annonynous"
            },
        };

        public static IEnumerable<QuotesViewModel> Inputs => QuotesDb;

        public static void AddQuotes(QuotesViewModel input)
        {
            //Inputs.Add(input);
        }
    }
}

RandomQuotes/Models/QuotesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RandomQuotes.Models
{
    public class QuotesViewModel : BaseEntity
    {
        public int Id { get; set; }

        [Required]
        [MinLength(4)]
        [MaxLength(200)]
        public string Quote { get; set; }

        [Required]
        [MinLength(4)]
        [MaxLength(60)]
        public string Author { get; set; }
        
    }
}

RandomQuotes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using RandomQuotes.Data;
using RandomQuotes.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RandomQuotes.Controllers
{
    public class HomeController : Controller
    {        
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RandomQuotes/Controllers/QuoteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RandomQuotes.Data;
using RandomQuotes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RandomQuotes.Controllers
{
    public class QuoteController : Controller
    {
        EntitiesContext dbcontext = new EntitiesContext();
        public IActionResult Index()
        {
            Random random = new Random();
            //var res = dbcontext.Quotes.AsNoTracking().OrderByDescending(q => q.Quote);
            var res = dbcontext.Quotes.OrderBy(emp => Guid.NewGuid()).AsNoTracking();
            return View(res);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(QuotesViewModel quotesModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    //ModelState.Clear();
                    return View();
                }
                else
                {
                    dbcontext.Quotes.Add(quotesModel);
                    dbcontext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        public IActionResult Edit (int id)
        {
            try
            {
                var result = dbcontext.Quotes.Where(q => q.Id == id).FirstOrDefault();
                return View("Edit", result);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public IActionResult Edit(QuotesViewModel edit)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    dbcontext.Quotes.Update(edit);
                    dbcontext.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Edit", edit);
                }
            }
            catch (Exception)
            {
                return View("Edit", edit);
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                var deleteQuote = dbcontext.Quotes.Where(q => q.Id == id).FirstOrDefault();
                if (deleteQuote != null )
                {
                    dbcontext.Quotes.Remove(deleteQuote);
                    dbcontext.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }              
            }
            catch (Exception)
            {
                return View();
            }
        }

    }
}

RandomQuotes/Views/Home/Index.cshtml
@model RandomQuotes.Models.QuotesViewModel
@using RandomQuotes.Controllers
@{
    ViewData["Title"] = "Quotes Home";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
    </div>
    <div class="text-center">
        <span>
            <a class="btn btn-primary" asp-controller="Quote" asp-action="Index">View Quotes</a>
        </span>
        <span>
            <a class="btn btn-primary" asp-controller="Quote" asp-action="Add">Add a Quote</a>
        </span>
    </div>
</body>
</html>

RandomQuotes/Views/Quote/Add.cshtml
@model RandomQuotes.Models.QuotesViewModel
@{
    ViewData["Title"] = "Adding Quote";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <form asp-action="Add" method="post">
        <h1>Add a new Quote</h1>
        <div>
            <label asp-for="Quote">Enter Quote:</label>
            <input asp-for="Quote" />
            <span asp-validation-for="Quote" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Author">Provide Author</label>
            <input asp-for="Author" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</body>
</html>

RandomQuotes/Views/Quote/Edit.cshtml
@model RandomQuotes.Models.QuotesViewModel
@{
    ViewData["Title"] = "Edit Quote";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <form asp-action="Edit" method="post">
        <h1>Edit a Quote</h1>
        <div>
            <label asp-for="Quote">Enter Quote:</label>
            <input asp-for="Quote" />
            <span asp-validation-for="Quote" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Author">Provide Author</label>
            <input asp-for="Author" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</body>
</html>

RandomQuotes/Views/Quote/Index.cshtml
@model IQueryable<RandomQuotes.Models.QuotesViewModel>
@using Humanizer

@{
    ViewData["Title"] = "Quotes Home";
}

<div class="text-center">
    <h1 class="display-4">Quotes Home</h1>
</div>
<div class="text-center">
    <span>
        <a class="btn btn-primary" asp-action="Add">Add a Quote</a>
    </span>
</div>

<div>
    @foreach (var r in Model)
    {
    <div class="jumbotron">
        <p class="text-primary">@r.Quote</p>
        <span class="text-muted">By @r.Author,</span>
        <span class="">Created @r.CreatedAt.Humanize()</span>
        <div>
            <span>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@r.Id">Edit</a>
            </span>
            <span>
                <a class="btn btn-primary" asp-action="Delete" asp-route-id="@r.Id">Delete</a>
            </span>
        </div>
    </div>
    }
</div>

RandomQuotes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Slimcent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RandomQuotes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RandomQuotes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>